#!/usr/bin/env python
"""Export the appendix per-generator table (`tab:clip:test_results_detail`) to `reproduction/revision_export/`.

Reads only what `scripts/finalexp/run_appendix_per_generator.py` produced — no recompute, no
lookups into `results/` — so the shipped table and its provenance record cannot drift apart. The
paper repo replaces its inline Table 13 with `\\input{}` of the .tex written here.

Display names come from `reproduction/config/mappings.yaml` — `model_name_map` for the trained models across
the top, and the **per-corpus** `<dataset>_source_map` for the generator rows. Per-corpus matters:
the same raw id is spelled differently by corpus there (`FLUX.1-dev` is `FluxDev` under
SynthBuster+ and `FLUXDev` under SynthCLIC), so a single global map would silently pick one.

Writes:
  * tables/clip_per_generator_detail.csv           test_corpus, generator, generator_display, train_set, acc, ap, n_fake, n_real
  * tables/clip_per_generator_detail_acceptance.csv the 12-cell check against e3_cross_matrix_mAP.csv
  * tex/clip_per_generator_detail.tex               the rendered table
  * tables/clip_per_generator_detail_run_meta.json  git commit, input sha256s, recipe, threshold, pairing
  * clip_per_generator_detail_README.md             how to read it + the acceptance table

    python scripts/export/export_per_generator_table.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pandas as pd
import yaml

ARTIFACTS = Path("reproduction/experiments/final_consolidation/TableB-per-generator/artifacts")
EXPORT = Path("revision_export")
MAPPINGS = Path("reproduction/config/mappings.yaml")

# Column order across the table, and the row-block order down it.
TRAIN_ORDER = ["synthclic", "synthbuster-plus", "cnnspot", "combined"]
CORPUS_ORDER = ["synthclic", "synthbuster-plus", "cnnspot"]


def _norm(dataset: str) -> str:
    """Dataset label ('synthbuster-plus') -> mappings-yaml key stem ('synthbuster_plus')."""
    return dataset.replace("-", "_")


def load_mappings(path: Path = MAPPINGS) -> dict:
    return yaml.safe_load(path.read_text())


def model_labels(maps: dict) -> dict[str, str]:
    """Trained-model display names, `model_name_map` first and `ds_name_map` as the fallback."""
    model_map, ds_map = maps.get("model_name_map", {}), maps.get("ds_name_map", {})
    labels = {}
    for name in dict.fromkeys(TRAIN_ORDER + CORPUS_ORDER):
        key = _norm(name)
        if key not in model_map and key not in ds_map:
            raise KeyError(f"{MAPPINGS}: no model_name_map/ds_name_map entry for {name!r}")
        labels[name] = model_map.get(key, ds_map.get(key))
    return labels


def generator_labels(maps: dict, detail: pd.DataFrame) -> dict[tuple[str, str], str]:
    """`(test_corpus, raw source) -> display name`, from each corpus's own `*_source_map`.

    Unmapped generators raise rather than falling through to the raw id: a table that mixes
    `SD1.4` with `stable-diffusion-1-3` reads as two different things, and the failure would be
    invisible in a 38-row appendix.
    """
    labels, missing = {}, []
    for corpus in CORPUS_ORDER:
        src_map = maps.get(f"{_norm(corpus)}_source_map")
        if not src_map:
            raise KeyError(f"{MAPPINGS}: no {_norm(corpus)}_source_map")
        for gen in detail[detail.test_corpus == corpus].generator.unique():
            if gen not in src_map:
                missing.append(f"{corpus}/{gen}")
            else:
                labels[(corpus, gen)] = src_map[gen]
    if missing:
        raise KeyError(f"{MAPPINGS}: no source-map entry for {', '.join(sorted(missing))}")
    return labels


def tex_escape(name: str) -> str:
    return name.replace("_", r"\_")


def render_tex(detail: pd.DataFrame, summary: dict, LABEL: dict[str, str]) -> str:
    thr = summary["threshold_rule"]
    pairing = summary["real_pairing"]
    lines = [
        "% Generated by scripts/export/export_per_generator_table.py — do not edit by hand.",
        "% Source: reproduction/experiments/final_consolidation/TableB-per-generator/",
        "\\begin{table}[!ht]",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{llrrrrrrrr}",
        "\\toprule",
        " & & "
        + " & ".join(f"\\multicolumn{{2}}{{c}}{{{LABEL[t]}}}" for t in TRAIN_ORDER)
        + " \\\\",
        " ".join(f"\\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(len(TRAIN_ORDER))),
        "Test set & Generator & " + " & ".join(["ACC & AP"] * len(TRAIN_ORDER)) + " \\\\",
    ]
    for corpus in CORPUS_ORDER:
        block = detail[detail.test_corpus == corpus]
        # Ordered by the *displayed* name, so the rendered block reads alphabetically.
        gens = (
            block[["generator", "generator_display"]]
            .drop_duplicates()
            .sort_values("generator_display", key=lambda s: s.str.lower())
        )
        lines.append("\\midrule")
        lines.append(f"\\multirow{{{len(gens) + 1}}}{{*}}{{{LABEL[corpus]}}}")
        for gen, shown in gens.itertuples(index=False):
            cells = []
            for train in TRAIN_ORDER:
                r = block[(block.generator == gen) & (block.train_set == train)]
                cells += (
                    [f"{float(r.iloc[0]['acc']):.2f}", f"{float(r.iloc[0]['ap']):.2f}"]
                    if len(r)
                    else ["--", "--"]
                )
            lines.append(f"& {tex_escape(shown)} & " + " & ".join(cells) + " \\\\")
        lines.append(f"\\cmidrule(l){{2-{2 + 2 * len(TRAIN_ORDER)}}}")
        means = []
        for train in TRAIN_ORDER:
            col = block[block.train_set == train]
            means += [f"{col['acc'].mean():.2f}", f"{col['ap'].mean():.2f}"]
        lines.append(
            "& \\textit{mean} & " + " & ".join(f"\\textit{{{m}}}" for m in means) + " \\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Per-generator detection performance of the CLIP linear head "
        "($D_h$, 1024-d frozen \\texttt{pooler\\_output}), for each training set (columns) on each "
        "test set (rows). AP is the per-generator average precision of the paper's Convention~A: "
        "on \\cnnspot{} each generator is scored against \\emph{its own} real images "
        f"(\\texttt{{{pairing['cnnspot']}}} pairing), on \\synthclic{{}} and \\synthbp{{}} against the "
        f"single shared real pool (\\texttt{{{pairing['synthclic']}}} pairing). ACC uses the head's own "
        "decision rule, $\\hat{p} > 0.5$ (equivalently logit $z > 0$), applied uniformly to every "
        "cell and computed on the same generator group as AP; no threshold is tuned on any test "
        "set. Per-column means reproduce the cross-dataset matrix of Table~\\ref{tab:rev:e3_cross}. "
        "All heads are trained under one matched recipe on frozen cached features without "
        "augmentation.}",
        "\\label{tab:clip:test_results_detail}",
        "\\end{table}",
    ]
    assert thr  # the threshold rule is stated in the caption above; keep them in one place
    return "\n".join(lines) + "\n"


def _naming_notes(detail: pd.DataFrame) -> list[str]:
    """Flag raw ids that `reproduction/config/mappings.yaml` spells differently in different corpora.

    Harmless in a per-corpus figure; visible in this table, where the two spellings sit in blocks a
    few rows apart. Reported rather than silently unified — the config is the authority.
    """
    pairs = detail[["generator", "generator_display"]].drop_duplicates()
    clashes = {
        gen: sorted(g.generator_display.unique())
        for gen, g in pairs.groupby("generator")
        if g.generator_display.nunique() > 1
    }
    if not clashes:
        return []
    return [
        "> **Naming note.** `reproduction/config/mappings.yaml` gives these generators different display names "
        "per corpus, so both spellings appear in the rendered table: "
        + "; ".join(f"`{gen}` -> {' / '.join(names)}" for gen, names in sorted(clashes.items()))
        + ". Applied as configured — unify the config if one spelling is wanted throughout.",
        "",
    ]


def render_readme(
    detail: pd.DataFrame,
    acceptance: pd.DataFrame,
    summary: dict,
    meta: dict,
    LABEL: dict[str, str],
) -> str:
    acc = acceptance.copy()
    acc["test corpus"] = acc.test_corpus.map(LABEL)
    acc["train set"] = acc.train_set.map(LABEL)
    acc["status"] = [
        "known frame mismatch" if k else ("ok" if a else "FAIL")
        for a, k in zip(acc.agrees_2dp, acc.known_frame_mismatch)
    ]
    for c in ("column_mean_ap", "authoritative_mAP", "delta", "manuscript_column_mean"):
        acc[c] = acc[c].map(lambda v: f"{v:+.4f}" if c == "delta" else f"{v:.4f}")
    cols = {
        "test corpus": "test corpus",
        "train set": "train set",
        "column_mean_ap": "generated col mean",
        "authoritative_mAP": "e3_cross_matrix",
        "delta": "Δ",
        "manuscript_column_mean": "old table col mean",
        "n_generators": "rows",
        "status": "status",
    }
    tbl = acc[list(cols)].rename(columns=cols)
    md = ["| " + " | ".join(tbl.columns) + " |", "|" + "---|" * len(tbl.columns)]
    for _, r in tbl.iterrows():
        md.append("| " + " | ".join(str(v) for v in r.to_list()) + " |")

    eq = pd.read_csv(ARTIFACTS / "recipe_equivalence.csv")
    eq_md = [
        "| train set | test corpus | refit mAP | shipped cell | Δ |",
        "|---|---|---|---|---|",
    ] + [
        f"| {LABEL[r.train_set]} | {LABEL[r.test_corpus]} | {r.mAP_refit:.4f} | "
        f"{r.mAP_table:.4f} | {r.delta:+.4f} |"
        for _, r in eq.iterrows()
    ]

    ngen = summary["n_generators_per_corpus"]
    return "\n".join(
        [
            "# `clip_per_generator_detail` — the appendix per-generator table",
            "",
            f"Generated {meta['started_at']} from git `{meta['git']['commit'][:12]}` by",
            "`scripts/finalexp/run_appendix_per_generator.py` + "
            "`scripts/export/export_per_generator_table.py`.",
            "",
            "Replaces the manuscript's inline Table 13 (`\\label{tab:clip:test_results_detail}`) "
            "with a generated `\\input{}`. Every cell now comes from **one** detector definition, "
            "the same one main Table 3 reports.",
            "",
            "## What the detector is",
            "",
            summary["detector"] + ".",
            "",
            "```",
            json.dumps(summary["recipe"], indent=2),
            "```",
            "",
            f"- **Threshold rule.** {summary['threshold_rule']}",
            "- **Real pairing.** "
            + ", ".join(f"{LABEL[k]} `{v}`" for k, v in summary["real_pairing"].items())
            + ".",
            f"- **Evaluated on.** The `{summary['eval_split']}` split of each corpus: "
            + ", ".join(f"{LABEL[k]} {ngen[k]} generators" for k in CORPUS_ORDER)
            + f" ({len(detail)} cells over {len(TRAIN_ORDER)} training sets).",
            "",
            "## Display names",
            "",
            f"Row and column labels come from `{MAPPINGS}` — `model_name_map` for the trained "
            "models across the top, and each corpus's own `<dataset>_source_map` for the generator "
            "rows. The CSV keeps the raw ids in `generator` / `train_set` / `test_corpus` (they are "
            "the join keys into the snapshot and the E3 predictions) and carries the rendered label "
            "alongside in `generator_display`. An unmapped generator is a hard error, not a "
            "fall-through to the raw id.",
            "",
            *_naming_notes(detail),
            "## Acceptance check",
            "",
            "The generated per-training-set column means against "
            "`reproduction/revision_export/tables/e3_cross_matrix_mAP.csv`, the matrix behind main Table 3:",
            "",
            *md,
            "",
            (
                "**Result: passed"
                + (
                    "** — all 12 cells agree to 2 decimals."
                    if summary["acceptance"]["agree_2dp"] == summary["acceptance"]["cells"]
                    else " with one recorded exception** — see below."
                )
            ),
            "",
            "### The one exception",
            "",
            "`Combined -> CNNSpot` is the only authoritative cell measured on a different "
            "population. The E3 CNNSpot column is evaluated on the **full CNNSpot benchmark test "
            "set** (108,310 images, 21 generators) for the CNNSpot-, SynthBuster+- and "
            "SynthCLIC-trained heads, but the later combined run only ever scored **cnnspot-small** "
            "(4,000 images, 20 generators). Its 0.8982 is therefore not comparable with the other "
            "three cells of that column. This table evaluates all four training sets on the full "
            "frame, which is what the manuscript's 21-row CNNSpot block requires.",
            "",
            "**Recommended paper-side edit:** update `e3_cross_matrix_mAP.csv` / "
            "`tex/e3_cross_dataset_mAP.tex`'s `combined -> CNNSpot` cell from **0.8982** to "
            f"**{acc[(acc.train_set == 'combined') & (acc.test_corpus == 'cnnspot')].column_mean_ap.iloc[0]}** "
            "so the whole column shares one evaluation population. Left unapplied here: it is a "
            "main-text number, not this table's to change.",
            "",
            "### Recipe equivalence",
            "",
            "Refitting each training set with the F1 trainer (seed 123) and scoring the two corpora "
            "whose test splits are open — the check that the reused E3 predictions really are the "
            "F1 estimator. SynthBuster+ test is excluded on purpose (see below).",
            "",
            *eq_md,
            "",
            "## SynthBuster+ test access",
            "",
            summary["sb_plus_test_access"],
            "",
            "## Files",
            "",
            "| file | contents |",
            "|---|---|",
            "| `tables/clip_per_generator_detail.csv` | the table as data (raw ids + "
            "`generator_display`) |",
            "| `tables/clip_per_generator_detail_acceptance.csv` | the 12-cell check above |",
            "| `tex/clip_per_generator_detail.tex` | the rendered table, `\\input{}`-able |",
            "| `tables/clip_per_generator_detail_run_meta.json` | git commit, input sha256s, recipe, "
            "threshold, pairing |",
            "",
        ]
    )


def main() -> None:
    detail = pd.read_csv(ARTIFACTS / "per_generator_detail.csv")
    acceptance = pd.read_csv(ARTIFACTS / "acceptance.csv")
    summary = json.loads((ARTIFACTS / "summary.json").read_text())
    meta = json.loads((ARTIFACTS / "run_meta.json").read_text())

    if not summary["acceptance"]["passed"]:
        raise SystemExit(
            "Refusing to export: the acceptance check has unexplained failures.\n"
            f"{summary['acceptance']['unexplained_failures']}"
        )

    maps = load_mappings()
    labels = model_labels(maps)
    gen_labels = generator_labels(maps, detail)
    detail["generator_display"] = [
        gen_labels[(c, g)] for c, g in zip(detail.test_corpus, detail.generator)
    ]

    (EXPORT / "tables").mkdir(parents=True, exist_ok=True)
    (EXPORT / "tex").mkdir(parents=True, exist_ok=True)

    out_cols = [
        "test_corpus",
        "generator",
        "generator_display",
        "train_set",
        "acc",
        "ap",
        "n_fake",
        "n_real",
    ]
    detail[out_cols].to_csv(EXPORT / "tables/clip_per_generator_detail.csv", index=False)
    acceptance.to_csv(EXPORT / "tables/clip_per_generator_detail_acceptance.csv", index=False)
    (EXPORT / "tex/clip_per_generator_detail.tex").write_text(render_tex(detail, summary, labels))
    shutil.copy2(
        ARTIFACTS / "run_meta.json", EXPORT / "tables/clip_per_generator_detail_run_meta.json"
    )
    (EXPORT / "clip_per_generator_detail_README.md").write_text(
        render_readme(detail, acceptance, summary, meta, labels)
    )

    print(f"  {len(detail)} rows -> {EXPORT}/tables/clip_per_generator_detail.csv")
    print(f"  display names from {MAPPINGS}")
    print(f"  {EXPORT}/tex/clip_per_generator_detail.tex")
    print(f"  {EXPORT}/tables/clip_per_generator_detail_run_meta.json")
    print(f"  {EXPORT}/clip_per_generator_detail_README.md")


if __name__ == "__main__":
    main()
